---
sudo: false
language: perl6
perl6:
  - latest
install:
  - rakudobrew build zef
  - zef install JSON::Tiny
before_script:
  - git clone https://github.com/exercism/x-common.git
  - bin/fetch-configlet
script:
  - bin/configlet .
  - prove -re perl6
